# Generated by Django 3.2.3 on 2021-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('apelido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(choices=[('pt', 'Portugal'), ('br', 'Brasil'), ('esp', 'Espanha'), ('uk', 'Reino Unido'), ('ale', 'Alemanha'), ('bel', 'Bélgica'), ('eua', 'Estados Unidos')], default='', max_length=9)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
