# Generated by Django 3.2.3 on 2021-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clareza', models.CharField(default=3, max_length=10)),
                ('rigor', models.CharField(default=3, max_length=10)),
                ('precisao', models.CharField(default=3, max_length=10)),
                ('optimizacao', models.BooleanField(default=False, verbose_name='Boa optimização para telemóvel')),
                ('tempoResposta', models.BooleanField(default=False, verbose_name='Tempo de resposta do Website')),
                ('facilUsar', models.BooleanField(default=False, verbose_name='Fácil de Usar')),
                ('facilLer', models.BooleanField(default=False, verbose_name='Fácil de Ler')),
                ('feedBack', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('apelido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(choices=[('pt', 'Portugal'), ('br', 'Brasil'), ('esp', 'Espanha'), ('uk', 'Reino Unido'), ('ale', 'Alemanha'), ('bel', 'Bélgica'), ('eua', 'Estados Unidos')], default='', max_length=20)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
